### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/grep#3]
- [x] Флаги `-i` и `-v` не учитываются при использовании регулярных выражений. 
- [x] По условию задания в случае использования флага `-r` на консоль должны выводиться только строки, **содержащие** регулярное выражние. У Вас выводятся строки, которые **полностью соответствуют** регулярному выражению.
- [x] Неэффективно реализована проверка на соответствие регулярному выражению. Подробности см. [здесь](https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches). 
- [x] Связку
  ```
  if (inv && !someCondition)
    ...
  if (!inv && someCondition)
    ...
  ```
  можно сократить до проверки одного логического выражения.

**Comment by GladkovaEkaterina** [comment]
исправила

**Comment by JohnKhandygo** [comment]
На будущее связки типа 
```
if (!ptr.matcher(tmp).find() && inv)
  ...
if (ptr.matcher(tmp).find() && !inv)
  ...
```
и
```
if (inv && !line.contains(word) || !inv && line.contains(word))
  ...
```
можно записать как 
```
if (inv ^ someOtherConsition)
  ...
```
В java `^` --- это операция xor (исключающее или), которая дает `true` тогда и только тогда, когда только один из аргументов `true`.
