### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/grep#4]
Вам осталось чуть-чуть исправить второе задание, поэтому предлагаю подумать над условием третьего. Есть несколько вариантов:
1. Получаете стандартное третье задание на написание графического приложения на Swing/JavaFX
2. Можете придумать свой вариант графического приложения, мы его обсудим и дополним/упростим по необходимости. По сложности должно получиться что-то типа многопользовательских шашек на одном компьютере.
3. Если Вам интересны какие-то конкретные направление в программировании (например, базы данных, web, Android) можно попробовать придумать задание с ипользованием этих технологий. 

Какой вариант Вам нравится больше всего?

**Comment by JohnKhandygo** [comment]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Шашки рэндзю**
Реализовать игру Шашки рэндзю для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Рэндзю)

**Comment by GladkovaEkaterina** [comment]
https://github.com/GladkovaEkaterina/Renju

**Comment by GladkovaEkaterina** [comment]
написала логику, а с остальным всё не очень хорошо...

**Comment by JohnKhandygo** [comment]
Перенес описание задания в новый репозиторий, все замечания будут появляться там.
